package net.minecraft.world.level.chunk;

import net.minecraft.SharedConstants;
import net.minecraft.core.*;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.*;
import net.minecraft.world.level.biome.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.lighting.LevelLightEngine;

/** Native ProtoChunk contract; no world is generated by this class. */
public final class FloodBoundarySmoke {
    private static int checks;
    private static void check(boolean value,String why){if(!value)throw new AssertionError(why);checks++;}
    private static ProtoChunk fixture(){
        var biome=new Biome.BiomeBuilder().hasPrecipitation(false).temperature(.5f).downfall(0)
            .generationSettings(BiomeGenerationSettings.EMPTY).mobSpawnSettings(MobSpawnSettings.EMPTY)
            .specialEffects(new BiomeSpecialEffects.Builder().waterColor(0).build()).build();
        var holder=Holder.direct(biome);var ids=new IdMapper<Holder<Biome>>();ids.add(holder);
        // AIR is intentional: section counters must agree with the palette. The
        // scanned band is explicitly filled with stone below.
        var factory=new PalettedContainerFactory(Strategy.createForBlockStates(Block.BLOCK_STATE_REGISTRY),Blocks.AIR.defaultBlockState(),null,Strategy.createForBiomes(ids),holder,null,null);
        var chunk=new ProtoChunk(new ChunkPos(0,0),UpgradeData.EMPTY,LevelHeightAccessor.create(-512,1024),factory,null);
        chunk.setLightEngine(LevelLightEngine.EMPTY);return chunk;
    }
    private static void set(ProtoChunk c,int x,int y,int z,Block block){c.setBlockState(new BlockPos(x,y,z),block.defaultBlockState(),0);}
    public static void main(String[] args){
        var out=System.out;SharedConstants.tryDetectVersion();Bootstrap.bootStrap();var c=fixture();
        for(int y=NeverOverworldFloodBoundaryR11.SCAN_MIN_Y;y<=NeverOverworldFloodBoundaryR11.SCAN_MAX_Y;y++)
            for(int z=0;z<16;z++)for(int x=0;x<16;x++)set(c,x,y,z,Blocks.STONE);
        // One component crosses the owner edge: it is part of the shallow flooded network.
        for(int y=80;y<=82;y++)for(int z=3;z<=8;z++)for(int x=0;x<=5;x++)set(c,x,y,z,Blocks.AIR);
        // An entirely owner-local sealed room stays dry.
        for(int y=90;y<=92;y++)for(int z=8;z<=10;z++)for(int x=8;x<=10;x++)set(c,x,y,z,Blocks.AIR);
        // A boundary room below the policy band stays dry.
        for(int y=-90;y<=-88;y++)for(int z=1;z<=3;z++)for(int x=0;x<=2;x++)set(c,x,y,z,Blocks.AIR);
        int changed=NeverOverworldFloodBoundaryR11.floodBoundaryComponents(c);
        check(changed==108,"boundary component changed="+changed);
        check(c.getBlockState(new BlockPos(0,80,3)).is(Blocks.WATER),"edge room water");
        check(c.getBlockState(new BlockPos(5,82,8)).is(Blocks.WATER),"whole boundary component water");
        check(c.getBlockState(new BlockPos(9,91,9)).isAir(),"sealed room preserved");
        check(c.getBlockState(new BlockPos(0,-89,2)).isAir(),"deep room preserved");
        check(NeverOverworldFloodBoundaryR11.floodBoundaryComponents(c)==0,"idempotent");
        out.println("PASS FloodBoundarySmoke checks="+checks);
    }
}
